# Generated by Django 5.2.12 on 2026-04-07 13:43

import platform_app.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('platform_app', '0002_email_verification_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', platform_app.models.users.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='email_verif_user_id_af07a7_idx',
            old_name='email_ver_user_sent_idx',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=platform_app.models.users._default_email_verification_expires_at),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
