# Generated by Django 5.2.12 on 2026-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0008_material_content_author_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cover_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
