# Generated by Django 5.2.12 on 2026-04-10 17:46

from django.db import migrations, models
from django.db.models import F


def backfill_published_at(apps, schema_editor):
    Post = apps.get_model("platform_app", "Post")
    Post.objects.filter(status="published", published_at__isnull=True).update(published_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0009_material_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_published_at, migrations.RunPython.noop),
    ]
